//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonQuestions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonQuestions.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action was aborted by the user..
        /// </summary>
        internal static string ActionAbortedMessage {
            get {
                return ResourceManager.GetString("ActionAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array Algorithms Menu.
        /// </summary>
        internal static string ArrayAlgorithmsMenuDescription {
            get {
                return ResourceManager.GetString("ArrayAlgorithmsMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array Algorithms.
        /// </summary>
        internal static string ArrayAlgorithmsMenuHeader {
            get {
                return ResourceManager.GetString("ArrayAlgorithmsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to continue....
        /// </summary>
        internal static string EnterToContinueMessage {
            get {
                return ResourceManager.GetString("EnterToContinueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the N&apos;th element in a fibonacci series..
        /// </summary>
        internal static string FibonacciNthElementMenuTitle {
            get {
                return ResourceManager.GetString("FibonacciNthElementMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} element in a fibonacci series is: {1}.
        /// </summary>
        internal static string FibonacciNthElementResultMessage {
            get {
                return ResourceManager.GetString("FibonacciNthElementResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter numbers for array devided by a comma.
        /// </summary>
        internal static string InputArrayMessage {
            get {
                return ResourceManager.GetString("InputArrayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a custom input..
        /// </summary>
        internal static string InputCustomMenuTitle {
            get {
                return ResourceManager.GetString("InputCustomMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter numbers for list devided by a comma.
        /// </summary>
        internal static string InputListMessage {
            get {
                return ResourceManager.GetString("InputListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a predefined input..
        /// </summary>
        internal static string InputPredefinedMenuTitle {
            get {
                return ResourceManager.GetString("InputPredefinedMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be an integer..
        /// </summary>
        internal static string IntegerFormatErrorMessage {
            get {
                return ResourceManager.GetString("IntegerFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Algorithm Library:.
        /// </summary>
        internal static string MainMenuHeader {
            get {
                return ResourceManager.GetString("MainMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;th Element From The Tail Of A Linked List Menu.
        /// </summary>
        internal static string NthFromTailHeader {
            get {
                return ResourceManager.GetString("NthFromTailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the N&apos;th element in a linked list, counting from the list&apos;s TAIL DOWN..
        /// </summary>
        internal static string NthFromTailMenuTitle {
            get {
                return ResourceManager.GetString("NthFromTailMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} value from the end is: {1}.
        /// </summary>
        internal static string NthFromTailResultMessage {
            get {
                return ResourceManager.GetString("NthFromTailResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the strongest subset in an array..
        /// </summary>
        internal static string StrongestSubestMenuTitle {
            get {
                return ResourceManager.GetString("StrongestSubestMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongest Subset.
        /// </summary>
        internal static string StrongestSubsetHeader {
            get {
                return ResourceManager.GetString("StrongestSubsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strongest subset with a sum of {0} is: {1}.
        /// </summary>
        internal static string StrongestSubsetResultMessage {
            get {
                return ResourceManager.GetString("StrongestSubsetResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongest Subsets Sums.
        /// </summary>
        internal static string StrongestSubsetSumsHeader {
            get {
                return ResourceManager.GetString("StrongestSubsetSumsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the strongest subsets sums using recurrence relation array..
        /// </summary>
        internal static string StrongestSubsetSumsMenuTitle {
            get {
                return ResourceManager.GetString("StrongestSubsetSumsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strongest subset has a sum of {0}, highest subset sum array: {1}.
        /// </summary>
        internal static string StrongestSubsetSumsResultMessage {
            get {
                return ResourceManager.GetString("StrongestSubsetSumsResultMessage", resourceCulture);
            }
        }
    }
}
